version: '3.8'

services:
  btc-eth-notifier:
    build: .
    container_name: btc-eth-price-alert
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - price_data:/app/data

volumes:
  price_data:

